// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pb/orders.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A drink that can be ordered
type Drink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drink) Reset() {
	*x = Drink{}
	mi := &file_pb_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drink) ProtoMessage() {}

func (x *Drink) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drink.ProtoReflect.Descriptor instead.
func (*Drink) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{0}
}

func (x *Drink) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Drink) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Drink) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Drink) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Response for GetDrinks
type GetDrinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drinks        []*Drink               `protobuf:"bytes,1,rep,name=drinks,proto3" json:"drinks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDrinksResponse) Reset() {
	*x = GetDrinksResponse{}
	mi := &file_pb_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDrinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDrinksResponse) ProtoMessage() {}

func (x *GetDrinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDrinksResponse.ProtoReflect.Descriptor instead.
func (*GetDrinksResponse) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{1}
}

func (x *GetDrinksResponse) GetDrinks() []*Drink {
	if x != nil {
		return x.Drinks
	}
	return nil
}

// One line item in an order
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DrinkId       int32                  `protobuf:"varint,1,opt,name=drink_id,json=drinkId,proto3" json:"drink_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_pb_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{2}
}

func (x *OrderItem) GetDrinkId() int32 {
	if x != nil {
		return x.DrinkId
	}
	return 0
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Request for OrderDrink – we send several items at once
type OrderDrinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OrderItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDrinkRequest) Reset() {
	*x = OrderDrinkRequest{}
	mi := &file_pb_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDrinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDrinkRequest) ProtoMessage() {}

func (x *OrderDrinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDrinkRequest.ProtoReflect.Descriptor instead.
func (*OrderDrinkRequest) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{3}
}

func (x *OrderDrinkRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// Response for OrderDrink – just say if it worked
type OrderDrinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDrinkResponse) Reset() {
	*x = OrderDrinkResponse{}
	mi := &file_pb_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDrinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDrinkResponse) ProtoMessage() {}

func (x *OrderDrinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDrinkResponse.ProtoReflect.Descriptor instead.
func (*OrderDrinkResponse) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{4}
}

func (x *OrderDrinkResponse) GetSuccess() *wrapperspb.BoolValue {
	if x != nil {
		return x.Success
	}
	return nil
}

// Total ordered quantity per drink
type OrderTotal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drink         *Drink                 `protobuf:"bytes,1,opt,name=drink,proto3" json:"drink,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderTotal) Reset() {
	*x = OrderTotal{}
	mi := &file_pb_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTotal) ProtoMessage() {}

func (x *OrderTotal) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTotal.ProtoReflect.Descriptor instead.
func (*OrderTotal) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{5}
}

func (x *OrderTotal) GetDrink() *Drink {
	if x != nil {
		return x.Drink
	}
	return nil
}

func (x *OrderTotal) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Response for GetOrders
type GetOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Totals        []*OrderTotal          `protobuf:"bytes,1,rep,name=totals,proto3" json:"totals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse) Reset() {
	*x = GetOrdersResponse{}
	mi := &file_pb_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse) ProtoMessage() {}

func (x *GetOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrdersResponse) GetTotals() []*OrderTotal {
	if x != nil {
		return x.Totals
	}
	return nil
}

var File_pb_orders_proto protoreflect.FileDescriptor

const file_pb_orders_proto_rawDesc = "" +
	"\n" +
	"\x0fpb/orders.proto\x12\x06models\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"c\n" +
	"\x05Drink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\":\n" +
	"\x11GetDrinksResponse\x12%\n" +
	"\x06drinks\x18\x01 \x03(\v2\r.models.DrinkR\x06drinks\"B\n" +
	"\tOrderItem\x12\x19\n" +
	"\bdrink_id\x18\x01 \x01(\x05R\adrinkId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"<\n" +
	"\x11OrderDrinkRequest\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.models.OrderItemR\x05items\"J\n" +
	"\x12OrderDrinkResponse\x124\n" +
	"\asuccess\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\asuccess\"M\n" +
	"\n" +
	"OrderTotal\x12#\n" +
	"\x05drink\x18\x01 \x01(\v2\r.models.DrinkR\x05drink\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"?\n" +
	"\x11GetOrdersResponse\x12*\n" +
	"\x06totals\x18\x01 \x03(\v2\x12.models.OrderTotalR\x06totals2\xd3\x01\n" +
	"\fOrderService\x12>\n" +
	"\tGetDrinks\x12\x16.google.protobuf.Empty\x1a\x19.models.GetDrinksResponse\x12C\n" +
	"\n" +
	"OrderDrink\x12\x19.models.OrderDrinkRequest\x1a\x1a.models.OrderDrinkResponse\x12>\n" +
	"\tGetOrders\x12\x16.google.protobuf.Empty\x1a\x19.models.GetOrdersResponseB\tZ\aexc8/pbb\x06proto3"

var (
	file_pb_orders_proto_rawDescOnce sync.Once
	file_pb_orders_proto_rawDescData []byte
)

func file_pb_orders_proto_rawDescGZIP() []byte {
	file_pb_orders_proto_rawDescOnce.Do(func() {
		file_pb_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_orders_proto_rawDesc), len(file_pb_orders_proto_rawDesc)))
	})
	return file_pb_orders_proto_rawDescData
}

var file_pb_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_orders_proto_goTypes = []any{
	(*Drink)(nil),                // 0: models.Drink
	(*GetDrinksResponse)(nil),    // 1: models.GetDrinksResponse
	(*OrderItem)(nil),            // 2: models.OrderItem
	(*OrderDrinkRequest)(nil),    // 3: models.OrderDrinkRequest
	(*OrderDrinkResponse)(nil),   // 4: models.OrderDrinkResponse
	(*OrderTotal)(nil),           // 5: models.OrderTotal
	(*GetOrdersResponse)(nil),    // 6: models.GetOrdersResponse
	(*wrapperspb.BoolValue)(nil), // 7: google.protobuf.BoolValue
	(*emptypb.Empty)(nil),        // 8: google.protobuf.Empty
}
var file_pb_orders_proto_depIdxs = []int32{
	0, // 0: models.GetDrinksResponse.drinks:type_name -> models.Drink
	2, // 1: models.OrderDrinkRequest.items:type_name -> models.OrderItem
	7, // 2: models.OrderDrinkResponse.success:type_name -> google.protobuf.BoolValue
	0, // 3: models.OrderTotal.drink:type_name -> models.Drink
	5, // 4: models.GetOrdersResponse.totals:type_name -> models.OrderTotal
	8, // 5: models.OrderService.GetDrinks:input_type -> google.protobuf.Empty
	3, // 6: models.OrderService.OrderDrink:input_type -> models.OrderDrinkRequest
	8, // 7: models.OrderService.GetOrders:input_type -> google.protobuf.Empty
	1, // 8: models.OrderService.GetDrinks:output_type -> models.GetDrinksResponse
	4, // 9: models.OrderService.OrderDrink:output_type -> models.OrderDrinkResponse
	6, // 10: models.OrderService.GetOrders:output_type -> models.GetOrdersResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pb_orders_proto_init() }
func file_pb_orders_proto_init() {
	if File_pb_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_orders_proto_rawDesc), len(file_pb_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_orders_proto_goTypes,
		DependencyIndexes: file_pb_orders_proto_depIdxs,
		MessageInfos:      file_pb_orders_proto_msgTypes,
	}.Build()
	File_pb_orders_proto = out.File
	file_pb_orders_proto_goTypes = nil
	file_pb_orders_proto_depIdxs = nil
}
